### ISSUE TITLE
ValueError at /gallery/upload/ : Field 'id' expected a number but got ''.

### ISSUE THREAD

**Issue by wvzuilen** [Starcross/django-starcross-gallery#4]
Hi, first: great project ! I love the design. I'm trying to implement it for a personal project (and learning Django).
When I try to upload one (or more) files by 'drag-and-drop' I get an error:

`ValueError at /gallery/upload/ : Field 'id' expected a number but got ''.`

I've double-checked the migrations. I'm pretty sure they are correct. I can upload through the admin console without errors.

I'm running everything in a docker container with a default sqlite database.

I guess I'm doing something wrong, but I don't have a clue what. Do you?

**Traceback**
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/gallery/upload/

Django Version: 3.1
Python Version: 3.8.3
Installed Applications:
['gallery',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)

The above exception (invalid literal for int() with base 10: '') was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/gallery/views.py", line 78, in form_valid
    image.image_albums.add(form.data['apk'])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1126, in _add_items
    target_ids = self._get_target_ids(target_field_name, objs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1073, in _get_target_ids
    target_ids.add(target_field.get_prep_value(obj))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 977, in get_prep_value
    return self.target_field.get_prep_value(value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(

Exception Type: ValueError at /gallery/upload/
Exception Value: Field 'id' expected a number but got ''.
```

**Comment by Starcross** [comment]
Hi, your setup sounds ok. I tried using a docker container and Python 3.8 / Django 3.1, but did not encounter this issue.

The line in question adds the newly created image to the album itself. This uses an id which is a hidden field in a form on the album view page. You should be able to see this in the html

  <input type="hidden" name="apk" value="[the id number]"/>

You mentioned you can add images in the admin console. Could you check you can also add these images to albums?

**Comment by Starcross** [comment]
No issue identified / Unable to reproduce

**Comment by xvolte** [comment]
@Starcross 
Hello, 

I'm having similar problem, when i try to drag and drop a bunch of images in the "Album" part.
I have : 

![image](https://user-images.githubusercontent.com/21142611/99085264-44a0ae00-25c8-11eb-9e43-f8e1b4e4b421.png)

**Comment by Starcross** [comment]
Hi, would you be able to post the full traceback for this error?

I would also be interested to know the sizes of the files you are uploading. Thanks

**Comment by xvolte** [comment]
Does this help ?

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/gallery/upload/

Django Version: 3.1.3
Python Version: 3.8.5
Installed Applications:
['gallery',
 'web.apps.WebConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\MyProject\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\MyProject\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\MyProject\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\MyProject\lib\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\MyProject\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\MyProject\lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "C:\MyProject\lib\site-packages\gallery\views.py", line 79, in form_valid
    image = Image.objects.create(data=img_data)
  File "C:\MyProject\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\MyProject\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\MyProject\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\MyProject\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\MyProject\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\MyProject\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\MyProject\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\MyProject\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\MyProject\lib\site-packages\django\db\models\sql\compiler.py", line 1396, in execute_sql
    for sql, params in self.as_sql():
  File "C:\MyProject\lib\site-packages\django\db\models\sql\compiler.py", line 1339, in as_sql
    value_rows = [
  File "C:\MyProject\lib\site-packages\django\db\models\sql\compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\MyProject\lib\site-packages\django\db\models\sql\compiler.py", line 1340, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\MyProject\lib\site-packages\django\db\models\sql\compiler.py", line 1291, in pre_save_val
    return field.pre_save(obj, add=True)
  File "C:\MyProject\lib\site-packages\django\db\models\fields\files.py", line 307, in pre_save
    file.save(file.name, file.file, save=False)
  File "C:\MyProject\lib\site-packages\django\db\models\fields\files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "C:\MyProject\lib\site-packages\django\core\files\storage.py", line 52, in save
    return self._save(name, content)
  File "C:\MyProject\lib\site-packages\django\core\files\storage.py", line 262, in _save
    file_move_safe(content.temporary_file_path(), full_path)
  File "C:\MyProject\lib\site-packages\django\core\files\move.py", line 56, in file_move_safe
    with open(old_file_name, 'rb') as old_file:

Exception Type: FileNotFoundError at /gallery/upload/
Exception Value: [Errno 2] No such file or directory: 'C:\\Users\\XXXXX\\Desktop\\PNG\\TEMP\\kvdvwxlq.upload.png'

```

**Comment by xvolte** [comment]
@Starcross please let me know if you need anything else ?
What is your media config and you file upload settings and processors ? it is working on your side ?
From a brand New Django install and a brand new django-starcross-gallery install, i confirm that it does not work.

**Comment by Starcross** [comment]
I have found an issue relating to uploading smaller files (#8) which may be related to your problem. It's fixed (version 1.0.10) in case you'd like to try it. 

Your media settings are probably ok if you can upload via the admin and see the thumbnails appearing in the gallery page. Here's what I use (as with most of my django projects)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

**Comment by Starcross** [comment]
@xvolte I just noticed 'web.apps.WebConfig' in your settings. I'm not familiar with this, so you could remove it if it's not needed elsewhere in your project.

**Comment by xvolte** [comment]
I confirm it is resolved !
